sudo: required
services:
    - docker

before_install:
    - docker build -t jilsonjoseph/docker-react -f Dockerfile.dev .

script:
    - docker run jilsonjoseph/docker-react npm run test -- --coverage